# Generated by Django 3.2.16 on 2023-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
