# Generated by Django 3.2.16 on 2023-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_brand_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='国'),
        ),
    ]
