# Generated by Django 3.2.16 on 2023-01-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20230118_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.FloatField(blank=True, null=True, verbose_name='株価')),
                ('end_value', models.FloatField(blank=True, null=True, verbose_name='株価')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='株価')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='株価')),
                ('trade_date', models.DateField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.brand')),
            ],
        ),
    ]
