# Generated by Django 3.2.16 on 2023-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='industry_code_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='industry_code_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='scale_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='end_value',
            field=models.FloatField(blank=True, null=True, verbose_name='終値'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='高値'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='安値'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='start_value',
            field=models.FloatField(blank=True, null=True, verbose_name='始値'),
        ),
    ]
