# Generated by Django 3.2.16 on 2023-01-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20230121_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(auto_now=True, null=True)),
                ('start_value', models.FloatField(blank=True, null=True, verbose_name='始値')),
                ('end_value', models.FloatField(blank=True, null=True, verbose_name='終値')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='高値')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='安値')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='出来高')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
