# Generated by Django 3.2.16 on 2023-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20230121_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='brand_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
