# Generated by Django 3.2.16 on 2023-01-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_trades_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
