# Generated by Django 3.2.16 on 2023-01-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_trades_trade_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='end_value',
            new_name='close_value',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='max_value',
            new_name='high_value',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='min_value',
            new_name='low_value',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='start_value',
            new_name='open_value',
        ),
    ]
